api_hash: 7361e4e465303fd92c8ddc652f1e0341
api_id: 13554560
chat_id: -1001648761763
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
ids_to_retry: []
last_read_message_id: 245
media_types:
- audio
- photo
- video
- document
- voice
- video_note
